<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Console\**" />
    <EmbeddedResource Remove="Console\**" />
    <None Remove="Console\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Principal.Windows" Version="5.0.0" />
  </ItemGroup>

</Project>
